spring.application.name=auth-service
server.port=${SERVER_PORT:9000}
app.auth-server-url=${AUTH_SERVER_URL:http://localhost:8080}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect